In [14]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from sklearn.metrics import confusion_matrix, precision_score, classification_report
import pandas as pd
from sklearn.metrics import accuracy_score



In [8]:
# Step 1: Load the saved .keras model
model = load_model('../../sentimento_6m_sent_encoded_150_CHKP_drlee_ata.keras')  # Replace with your .keras model path

X_test =  vector = np.load('../../subsets/sentimento_6m_sent_encoded_X_test.npy')
y_test =  vector = np.load('../../subsets/sentimento_6m_sent_encoded_y_test.npy')

print(X_test[:5])

print(y_test[:5])


[[   0    0    0 ...   31    3 3260]
 [   0    0    0 ... 2975    7   31]
 [   0    0    0 ...   10    4   16]
 [   0    0    0 ... 2192    5 2134]
 [   0    0    0 ...    8  949  316]]
[0 0 1 0 1]


In [10]:
predictions = model.predict(X_test)


2/2 ━━━━━━━━━━━━━━━━━━━━ 7s 3s/step
[[0.40447846 0.32418165 0.27133998]
 [0.4045722  0.3240037  0.27142408]
 [0.37892774 0.35864314 0.2624291 ]
 [0.3910396  0.34022042 0.2687399 ]
 [0.38917708 0.3459021  0.26492074]
 [0.38353723 0.35380536 0.2626574 ]
 [0.38014802 0.35880083 0.26105112]
 [0.384652   0.3481284  0.26721963]
 [0.3807857  0.35502505 0.2641892 ]
 [0.3801478  0.3588006  0.26105154]
 [0.385223   0.35260653 0.26217043]
 [0.38018844 0.35893017 0.26088142]
 [0.38665038 0.35031223 0.2630373 ]
 [0.38015598 0.3588017  0.26104227]
 [0.3881418  0.34907454 0.26278368]
 [0.39122656 0.33984616 0.2689273 ]
 [0.38736886 0.34579134 0.26683983]
 [0.38063738 0.3539211  0.26544154]
 [0.3934678  0.34363848 0.26289374]
 [0.38017562 0.35871315 0.2611112 ]
 [0.38508296 0.35177448 0.2631425 ]
 [0.38079426 0.35518894 0.2640168 ]
 [0.38569066 0.35075065 0.26355863]
 [0.3957254  0.33349466 0.2707799 ]
 [0.39005855 0.34167075 0.26827076]
 [0.39648625 0.33461362 0.26890007]
 [0.3801326  0.35877067 0.26

In [11]:
predicted_classes = np.argmax(predictions, axis=1)
print(predicted_classes)
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
[0 0 1 0 1 1 1 0 1 2 0 2 1 1 0 0 0 1 1 1 2 1 1 0 2 0 1 2 0 1 1 1 1 1 1 1 1
 0 1 1 1 1]


In [15]:


# Step 3 (Optional): Process predictions based on task
if len(predictions.shape) > 1 and predictions.shape[-1] > 1:  # Multi-class classification
    predicted_classes = np.argmax(predictions, axis=1)
    true_classes = np.argmax(y_test, axis=1) if len(y_test.shape) > 1 else y_test
    print("Sample predicted classes:", predicted_classes[:5])
    print("Sample true classes:", true_classes[:5])
    # Optional: Verify accuracy matches evaluate
    custom_accuracy = accuracy_score(true_classes, predicted_classes)
    print(f"Custom computed accuracy: {custom_accuracy:.4f}")
else:  # Regression or binary classification
    predictions = predictions.flatten()  # Flatten if needed
    print("Sample predictions:", predictions[:5])
    if y_test.shape[-1] == 1:  # Regression or binary classification
        y_test = y_test.flatten()
        mse = tf.keras.metrics.mean_squared_error(y_test, predictions).numpy()
        print(f"Mean Squared Error: {mse:.4f}")

Sample predicted classes: [0 0 0 0 0]
Sample true classes: [0 0 1 0 1]
Custom computed accuracy: 0.2857
